### ISSUE TITLE
Error 500 from Server on Login

### ISSUE THREAD

**Issue by nbjayme** [ergonode/backend#251]
## Bug type
Symfony complains
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ErgonodeAuthenticationBundle" from namespace "Ergonode\Authentication".
!!  Did you forget a "use" statement for another namespace? in /var/www/src/Kernel.php:46
!!  Stack trace:
!!  #0 /var/www/vendor/symfony/http-kernel/Kernel.php(424): App\Kernel->registerBundles()
!!  #1 /var/www/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /var/www/vendor/symfony/framework-bundle/Console/Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /var/www/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /var/www/vendor/symfony/console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #5 /var/www/bin/console(43): Symfony\Component\Console\Application->run(Object in /var/www/src/Kernel.php on line 46
!!

## Current behavior
After working for number of days, backend now throws 500 to client.

**Comment by nbjayme** [comment]
Issue resolved

the module/authentication folder was missing or moved to another location.
placing back module/authentication solves it.
